//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouse.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emploee
    {
        public int IDEmploee { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public int IDGender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Email { get; set; }
        public string PersonalCode { get; set; }
        public int IDLogin { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Login Login { get; set; }
    }
}
