//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouse.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSupply
    {
        public int IDSupply { get; set; }
        public int IDProduct { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
