//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeHouse.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_AllProductInfo
    {
        public string Наименование { get; set; }
        public decimal Цена { get; set; }
        public int Количество { get; set; }
        public Nullable<int> Срок_годности { get; set; }
        public string Категория { get; set; }
    }
}
